name: hrk_analysis
version: 1.1.0

description: >-
  A library to accumulate required dart and flutter analysis options.
repository: https://github.com/hrishikesh-kadam/hrk_analysis.dart
topics:
  - analysis
  - lints

environment:
  sdk: ^3.0.0

dependencies:
  flutter_lints: ^5.0.0
