name: hrk_analysis
version: 0.1.0

description: >-
  A library to accumulate required dart and flutter analysis options.
repository: https://github.com/hrishikesh-kadam/hrk_analysis.dart
topics:
  - analysis
  - lints

environment:
  sdk: ^3.0.0

dependencies:
  flutter_lints: ">=2.0.2 <4.0.0"
